[build]
  publish = "_site"
  command = "npm run build"

[context.production.environment]
  SECRETS_SCAN_ENABLED = "false"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
